include(GoogleTest)

add_subdirectory(render)
add_subdirectory(util_test)
add_subdirectory(cmake_mod_test)
add_subdirectory(test_gtest)
add_subdirectory(tvid_mem_prof)
add_subdirectory(signal_test)
add_subdirectory(img_trans_net)
add_subdirectory(with_head)
add_subdirectory(comm_test)
add_subdirectory(hero_deploy_vt)