import QtQuick
import QtQuick.Window
// import org.freedesktop.gstreamer.Qt6GLVideoItem 1.0 // Dynamic generated by GStreamer Qt6 QML plugin

import Gentau.Foundation
import Gentau.BotHud

Window {
    id: bottomPane

    width: 1920
    height: 1080
    visible: true

    color: Qt.lighter(Style.grayBlue, 2.0)

    property real scaler: Math.min(bottomPane.width / 1920, bottomPane.height / 1080)

    property bool uiCapturesMouse: false

    BotHud {
        id: botHud

        anchors.fill: parent

        scaleFactor: bottomPane.scaler
    }

    // Item {
    //     anchors.fill: parent

    //     GstGLQt6VideoItem {
    //         id: video
    //         objectName: "videoItem"
    //         anchors.centerIn: parent
    //         width: parent.width
    //         height: parent.height
    //     }

    //     Text {
    //         text: "Hello, Taurus!"
    //         font.family: Style.orbitronFL.font.family
    //         color: Style.lightGreen
    //         font.pixelSize: 32
    //         anchors.centerIn: parent
    //     }
    // }

    Shortcut {
        sequence: "Escape"
        onActivated: Qt.quit()
    }
}
