pragma ComponentBehavior: Bound

import QtQuick
import QtQuick.Controls
import QtQuick.Window
// import org.freedesktop.gstreamer.Qt6GLVideoItem 1.0 // Dynamic generated by GStreamer Qt6 QML plugin

import Gentau.Foundation
import Gentau.BotHud
import Gentau.ConfPanel

Window {
    id: bottomPane

    width: 1920
    height: 1080
    visible: true

    color: Qt.lighter(Style.grayBlue, 2.0)

    property real scaler: Math.min(bottomPane.width / 1920, bottomPane.height / 1080)

    property bool uiCapturesMouse: false

    MouseArea {
        id: tempCursorMock

        anchors.fill: parent
        cursorShape: bottomPane.uiCapturesMouse ? Qt.ArrowCursor : Qt.BlankCursor
        acceptedButtons: Qt.NoButton
    }

    BotHud {
        id: botHud

        anchors.fill: parent

        scaleFactor: bottomPane.scaler
    }

    // Item {
    //     anchors.fill: parent

    //     GstGLQt6VideoItem {
    //         id: video
    //         objectName: "videoItem"
    //         anchors.centerIn: parent
    //         width: parent.width
    //         height: parent.height
    //     }

    //     Text {
    //         text: "Hello, Taurus!"
    //         font.family: Style.orbitronFL.font.family
    //         color: Style.lightGreen
    //         font.pixelSize: 32
    //         anchors.centerIn: parent
    //     }
    // }

    Shortcut {
        sequence: "P"
        autoRepeat: false
        context: Qt.ApplicationShortcut
        onActivated: {
            if (confLoader.active && confLoader.item) {
                confLoader.popup.close();
            } else {
                confLoader.active = true;
            }
        }
    }

    property int lastConfTabIndex: 0

    Loader {
        id: confLoader

        readonly property Popup popup: item as Popup

        anchors.fill: parent
        active: false

        sourceComponent: Component {
            ConfPanel {
                id: confPanel

                anchors.centerIn: parent

                initialTabIndex: bottomPane.lastConfTabIndex

                onClosed: confLoader.active = false;

                onAboutToShow: bottomPane.uiCapturesMouse = true;

                onAboutToHide: {
                    bottomPane.lastConfTabIndex = confPanel.currentTabIndex;
                    bottomPane.uiCapturesMouse = false;
                }

                Component.onCompleted: confPanel.open();

                scaleFactor: bottomPane.scaler
            }
        }
    }
}
